{"name": "The user should be able to view orders repository", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x005CA813+48355]\n\t(No symbol) [0x0055C4B1]\n\t(No symbol) [0x00465358]\n\t(No symbol) [0x0044D293]\n\t(No symbol) [0x004AE37B]\n\t(No symbol) [0x004BC473]\n\t(No symbol) [0x004AA536]\n\t(No symbol) [0x004882DC]\n\t(No symbol) [0x004893DD]\n\tGetHandleVerifier [0x0082AABD+2539405]\n\tGetHandleVerifier [0x0086A78F+2800735]\n\tGetHandleVerifier [0x0086456C+2775612]\n\tGetHandleVerifier [0x006551E0+616112]\n\t(No symbol) [0x00565F8C]\n\t(No symbol) [0x00562328]\n\t(No symbol) [0x0056240B]\n\t(No symbol) [0x00554FF7]\n\tBaseThreadInitThunk [0x76476839+25]\n\tRtlGetFullPathName_UEx [0x7708906F+1215]\n\tRtlGetFullPathName_UEx [0x7708903D+1165]\n\n", "trace": "  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 75, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 965, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 977, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "And Scroll through menu to view planning option", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x005CA813+48355]\n\t(No symbol) [0x0055C4B1]\n\t(No symbol) [0x00465358]\n\t(No symbol) [0x0044D293]\n\t(No symbol) [0x004AE37B]\n\t(No symbol) [0x004BC473]\n\t(No symbol) [0x004AA536]\n\t(No symbol) [0x004882DC]\n\t(No symbol) [0x004893DD]\n\tGetHandleVerifier [0x0082AABD+2539405]\n\tGetHandleVerifier [0x0086A78F+2800735]\n\tGetHandleVerifier [0x0086456C+2775612]\n\tGetHandleVerifier [0x006551E0+616112]\n\t(No symbol) [0x00565F8C]\n\t(No symbol) [0x00562328]\n\t(No symbol) [0x0056240B]\n\t(No symbol) [0x00554FF7]\n\tBaseThreadInitThunk [0x76476839+25]\n\tRtlGetFullPathName_UEx [0x7708906F+1215]\n\tRtlGetFullPathName_UEx [0x7708903D+1165]\n\n", "trace": "  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"Features\\environment.py\", line 75, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 965, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 977, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\akankshyad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1716787153653, "stop": 1716787153657}, {"name": "And Scroll through menu to view orders menu", "status": "skipped", "start": 1716787153658, "stop": 1716787153658}, {"name": "And Click on orders button", "status": "skipped", "start": 1716787153658, "stop": 1716787153658}], "start": 1716787152642, "stop": 1716787153658, "uuid": "8eed1465-6b51-4fd8-82a6-17b3cfb35195", "historyId": "8861ba84460d4043a237208c15b1b0a1", "fullName": "Verify the TMS functionality: The user should be able to view orders repository", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Orders"}, {"name": "feature", "value": "Verify the TMS functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}